### ISSUE TITLE
beammp-server: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by asamson23** [RouHim/beammp-container-image#14]
When attempting to run the docker container with the updated image for BeamMP, there is the error when attempting to run the docker container

**Comment by RouHim** [comment]
Hey @asamson23, thank you for the bug report. I'll have a look and keep you updated.

**Comment by asamson23** [comment]
The container is running under Docker version 20.10.14 on Unraid 6.10.3.

**Comment by asamson23** [comment]
As for the image of the executable, I took the one available on the official website

**Comment by RouHim** [comment]
Can you please pull the latest image and try again?

**Comment by asamson23** [comment]
Latest beammp-server image or latest docker image?

**Comment by RouHim** [comment]
latest container image

**Comment by asamson23** [comment]
The server was updated to the latest version and that's when the issues started to happen. The server is updated and was force updated to the latest version.

**Comment by RouHim** [comment]
Sorry I do not get you point, what do you exactly do? Can you please describe it step by step.

**Comment by asamson23** [comment]
Under the Docker tab in Unraid, under "Advanced view", there is a "force update" button to force a fetch from the Docker hub. 
![image](https://user-images.githubusercontent.com/2985967/184692078-2a95d5cb-4bd4-4a82-bc56-ea67a4aeccb2.png)
As for the executable, I went to the official website, grabbed the zip file, extracted the linux version and renamed it to "beammp-server"

**Comment by RouHim** [comment]
Ok it looks like unraid does not understand the new oci metadata format. Ok good hint, I'll set it to docker to be backwards compatible.

**Comment by RouHim** [comment]
I fixed it. If this pipe is done: https://github.com/RouHim/beammp-container-image/actions/runs/2862630418 you should pull the latest docker container image

**Comment by asamson23** [comment]
I pulled the latest image build once it got pushed on the docker hub, but I still get the same issue

**Comment by RouHim** [comment]
Ok, I lets have another try: https://github.com/RouHim/beammp-container-image/actions/runs/2862809638
Looks like openssl 1.1 is missing (Only 3) in 22.04

**Comment by RouHim** [comment]
Btw your mount point looks fishy, why to you mount the whole server folder to your host? If you want to install mods, only mount the beammp/Resources/Client to your host.

**Comment by asamson23** [comment]
> Ok, I lets have another try: https://github.com/RouHim/beammp-container-image/actions/runs/2862809638 Looks like openssl 1.1 is missing (Only 3) in 22.04

That fixed it!



> Btw your mount point looks fishy, why do you mount the whole server folder to your host? If you want to install mods, only mount the `beammp/Resources/Client` to your host.

As for the mount point on the host, it is the only way for me to be able to access the ressource folder so that I can load up mods on my server

**Comment by RouHim** [comment]
Yeah :) Great. But as I said, it's best to mount as little as possible, as described above only the client mods folder.
